### ISSUE TITLE
[META 321] Make log_level configuration option dynamic

### ISSUE THREAD

**Issue by basepi** [elastic/apm-agent-php#210]
Implementing elastic/apm#332
https://github.com/elastic/apm-agent-php/issues/134 is a prerequisite

Note that the implementation of this spec also includes adding the option to [Kibana](https://github.com/elastic/kibana/blob/master/x-pack/plugins/apm/common/agent_configuration/setting_definitions/general_settings.ts).

**Comment by felixbarny** [comment]
The PHP agent supports a [`NOTICE`](https://www.elastic.co/guide/en/apm/agent/php/current/configuration.html#configure-logging) log level which is not one of the [commonly agreed log levels](https://github.com/elastic/apm/blob/master/specs/agents/logging.md). Is there a specific reason why `NOTICE` is required for PHP or could it be removed?

**Comment by SergeyKleyman** [comment]
My thought process on deciding the levels was as follows:
1. I started with the PHP standard [PSR-3](https://www.php-fig.org/psr/psr-3/) which is AFAICS is direct mapping of [syslog severity levels](https://en.wikipedia.org/wiki/Syslog#Severity_level).
2. I merged `EMERGENCY`, `ALERT` and `CRITICAL` into `CRITICAL` because I didn't see the [syslog's distinction between them](https://en.wikipedia.org/wiki/Syslog#Severity_level) as relevant to the agent.
3. I added `TRACE` as the most verbose levels (and also a level under which the agent can log something that can be security sensitive - the agent should make best effort not to do that under less verbose levels).

So to answer your question
> Is there a specific reason why NOTICE is required for PHP or could it be removed?

No, there is not specific reason - it was just inherited from syslog so it can be removed. I do see some benefits to having it - to log something that might be an issue but the code logging it doesn't have enough information to definitely say one way or the other. The way I see it, `INFO` is purely informational (not for drawing attention to a potential problem) and `WARNING` is for drawing attention to a potential problem that doesn't raise to the level of `ERROR` (for example `WARNING` for problems that might affect performance while `ERROR` issues might affect correctness). So `NOTICE` between `WARNING` and `INFO` is a "nice to have" but it's not a "must".

Do you think PHP having `NOTICE` level might be an issue when getting `log_level` from central configuration (assuming that central configuration won't have it) or is your concern more about general consistency between the agents?

**Comment by felixbarny** [comment]
My only concern would just be the general cross-agent consistency. Does the PHP agent currently use the notice log level?

**Comment by SergeyKleyman** [comment]
Yes, the agent uses `NOTICE` in a few place (https://github.com/elastic/apm-agent-php/search?q=ifNoticeLevelEnabled - I see that the most of it is in component tests code) but it can be easily find-and-replace-ed by let's `WARNING`.

**Comment by SergeyKleyman** [comment]
And it's going to be somewhat a breaking change for [logging configuration](https://www.elastic.co/guide/en/apm/agent/php/current/configuration.html#configure-logging) but the agent is not GA yet so we are going to remove `NOTICE` it's better to do it before GA.

**Comment by felixbarny** [comment]
@SergeyKleyman, could you [link the PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) that fixed this?

**Comment by SergeyKleyman** [comment]
@felixbarny I am sorry - I was too quick in closing the issue. The PR (#635) still has some issues. You are right about missing link between PR and the issue - I will make sure to use them in the future.
