### ISSUE TITLE
ENV config should precede over ini config

### ISSUE THREAD

**Issue by JoniJnm** [elastic/apm-agent-php#741]
I have a default config for .ini files but I can't overwrite them with ENV config. Seems like the configuration first looks in ini file and if it exists returns the value.

The c php extension and the php library should look first in ENV vars

I created a test in c (I don't know how to solve it):

```c
--TEST--
Env configuration should precede ini configuration
--SKIPIF--
<?php if ( ! extension_loaded( 'elastic_apm' ) ) die( 'skip'.'Extension elastic_apm must be installed' ); ?>
--ENV--
ELASTIC_APM_ENABLED=true
--INI--
elastic_apm.enabled=false
--FILE--
<?php
declare(strict_types=1);
require __DIR__ . '/../tests_util/tests_util.php';

elasticApmAssertSame("getenv('ELASTIC_APM_ENABLED')", getenv('ELASTIC_APM_ENABLED'), 'true');
elasticApmAssertEqual("ini_get('elastic_apm.enabled')", ini_get('elastic_apm.enabled'), false);

elasticApmAssertSame("elastic_apm_is_enabled()", elastic_apm_is_enabled(), true);

echo 'Test completed'
?>
--EXPECT--
Test completed
```

And for php, I don't know how to create the test but the TracerBuilder sets the values of INI and ENV

https://github.com/elastic/apm-agent-php/blob/a457869b0c15e95b61a41bd75da7208a64b18c94/src/ElasticApm/Impl/TracerBuilder.php#L109-L114

So if the config is in the INI won't look at ENV 

https://github.com/elastic/apm-agent-php/blob/a457869b0c15e95b61a41bd75da7208a64b18c94/src/ElasticApm/Impl/Config/CompositeRawSnapshot.php#L46-L50

Seems like the solution is to change the order.

**Comment by macedd** [comment]
Resolved for me by using environment variables in the extension `.ini`

```
elastic_apm.enabled = ${ELASTIC_APM_ENABLED}
```

**Comment by SergeyKleyman** [comment]
@macedd Thank you for the proposal.
@JoniJnm does the solution proposed by @macedd work for you?

**Comment by JoniJnm** [comment]
how can I set a default value in the .ini file and later be able to overwrite it with an env var?

**Comment by SergeyKleyman** [comment]
@JoniJnm
> how can I set a default value in the .ini file and later be able to overwrite it with an env var?

Please take a look at an example at https://github.com/SergeyKleyman/elastic_apm_php_agent_aux/tree/main/issues/config_default_ini_specific_env

Setting default directly in php.ini is supported only from 8.3 (see https://github.com/php/php-src/pull/11351) so before it's released setting global default is only possible with environment variable as well as custom value per process as it's done in the example linked above.

Technically line
```
elastic_apm.service_name="${ELASTIC_APM_SERVICE_NAME}"
```
in `agent_config.ini` is redundant since result will be the same even if that line is removed.
From PHP 8.3 it will be possible to use default value:
```
elastic_apm.service_name="${ELASTIC_APM_SERVICE_NAME:-my_default_svc}"
```
thus not requiring setting global default with environment variable anymore.


Regarding 
> it is just change the order in the code

Unfortunately we cannot change the order in the code because it will introduce backward incompatible change and the existing code that relies on the current order will be broken.

Just in case we might get to a point in the future when we might reconsider this issue - could you please share why in your case it's preferable to set global default with `php.ini` and environment variable?

**Comment by JoniJnm** [comment]
ok, thanks.

In our company we have a php base image used by different projects. The idea is to have in this base image default values for apm (using the .ini file). Later, projects can overwritte them just using env vars.

Currectly each project is setting all the parameters.

We can survive, it just only a nice-to-have 😊

**Comment by SergeyKleyman** [comment]
@JoniJnm thank you for clarifying the use case.
We are closing it for now - we will revisit it if necessary.
