### ISSUE TITLE
Extremely long execution time for PHP scripts using version 1.8.3

### ISSUE THREAD

**Issue by tostiheld** [elastic/apm-agent-php#950]
**Describe the bug**
When upgrading to 1.8.3 from 1.7.2, we observed significantly longer execution times for our scripts in both PHP-FPM and on the CLI. The latency would increase to anywhere between 4-10 times as much. For example, cronjobs went from taking a couple seconds to taking up to 15 minutes and our response time would increase from 400ms to 4000ms.

Unfortunately I do not have more information than this (because I do not know a lot about the internals of this extension or PHP extensions in general), so let me know what kind of extra information I can provide.

**To Reproduce**
Our config:
```
elastic_apm.enabled = true
elastic_apm.api_key = "<redacted>"
elastic_apm.environment = "production"
elastic_apm.server_timeout = "2s"
elastic_apm.server_url = "<redacted>"
```
PHP version: 8.1.18
APM agent version: 1.8.3

I do not have a reproducer. However the issue is quite easy to replicate in our dev/test environment, so given some pointers I can try to create a reproducer.

**Expected behavior**
Latency consistent with APM agent version <1.8.3

**Comment by SergeyKleyman** [comment]
@tostiheld Thank you for letting us about this issue.
I have a hypothesis that long execution times you observe caused by the part of the agent sending the data to APM Server. I would like to ask you to try the following steps to verify if my assumption is correct:
- [ ] Please set [`disable_send` option](https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html#config-disable-send) to `true` and see how it affects the execution time
- [ ] Please set `async_backend_comm` option to `true` and see how it affects the execution time (don't forget to remove/comment out `disable_send` option set in the previous step - we would like to see effects of each option by itself)
- [ ] If you can create a simple minimal self-contained environment reproducing the issue (for example using docker) it will help us to resolve it much quicker. Thank you in advance :)

**Comment by intuibase** [comment]
@tostiheld could you please try with latest release?
If you're still experiencing issues, please follow previous comment and try to provide more details about the issue.
