### ISSUE TITLE
Error install agent 

### ISSUE THREAD

**Issue by nurhambali** [elastic/apm-agent-php#97]
hi, 
i try install apm-agent-php corresponding [**documentation**](https://github.com/elastic/apm-agent-php/blob/master/docs/setup.asciidoc) but I get an error during installation
![image](https://user-images.githubusercontent.com/18512905/88062280-d3f60180-cb92-11ea-8220-7e2ae5b81bc3.png)

- OS : Centos 7
- PHP: php 7.4

are there special requirements for the **Centos 7** operating system ?

**Comment by SergeyKleyman** [comment]
It seems the root cause for this issue is that CentOS 7 has quite an old version of gcc (C compiler) that defaults to very old (pre -C99) standard mode.

Could you please try?
```
CFLAGS="-std=gnu99" ./configure --enable-elastic_apm
```

instead of the following command from the [documentation](https://github.com/elastic/apm-agent-php/blob/master/docs/setup.asciidoc)

```
./configure --enable-elastic_apm
```

**Comment by nurhambali** [comment]
@SergeyKleyman 
Thank you for the solution for  install APM agent 
![image](https://user-images.githubusercontent.com/18512905/88181704-711b6d80-cc59-11ea-8421-3213f896d5d9.png)
